name: Java CI with Maven

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  check-application:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: run tests
      run: mvn test
    - name: Build with Maven
      run: mvn clean test -B package --file pom.xml
    - name: Run the JAR file
      run: java -jar target/*.jar
